version: "3"
services:
  web:
    container_name: "laravel-modern-cart-nginx"
    image: nginx:latest
    ports:
      - "8000:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /file_data/
      - ../storage/framework/:/source/storage/framework/
      - ../storage/logs/:/source/storage/logs/
      - ../app:/source/app
      - ../presets:/source/presets
      - ../bootstrap:/source/bootstrap
      - ../config:/source/config
      - ../database:/source/database
      - ../public:/source/public
      - ../resources:/source/resources
      - ../routes:/source/routes
      - ../tests:/source/tests
      - ../.env.example:/source/.env.example
      - ../.styleci.yml:/source/.styleci.yml
      - ../artisan:/source/artisan
      - ../composer.json:/source/composer.json
      - ../composer.lock:/source/composer.lock
      - ../package.json:/source/package.json
      - ../phpunit.xml:/source/phpunit.xml
      - ../server.php:/source/server.php
      - ../webpack.mix.js:/source/webpack.mix.js
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: "laravel-modern-cart-php"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    expose:
      - 9000
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /file_data/
      - ../storage/framework/:/source/storage/framework/
      - ../storage/logs/:/source/storage/logs/
      - ../app:/source/app
      - ../presets:/source/presets
      - ../bootstrap:/source/bootstrap
      - ../config:/source/config
      - ../database:/source/database
      - ../public:/source/public
      - ../resources:/source/resources
      - ../routes:/source/routes
      - ../tests:/source/tests
      - ../.env.example:/source/.env.example
      - ../.styleci.yml:/source/.styleci.yml
      - ../artisan:/source/artisan
      - ../composer.json:/source/composer.json
      - ../composer.lock:/source/composer.lock
      - ../package.json:/source/package.json
      - ../phpunit.xml:/source/phpunit.xml
      - ../server.php:/source/server.php
      - ../webpack.mix.js:/source/webpack.mix.js
      - ./php.ini:/usr/local/etc/php/php.ini
  mariadb:
    container_name: "mariadb"
    image: mariadb:latest
    restart: always
    expose:
        - 3306
    ports:
        - "3306:3306"
    volumes:
        - "./mariadb/conf.d:/etc/mysql/conf.d"
        - "/var/lib/mysql"
    environment:
        MARIADB_DATABASE: "modern_cart"
        MARIADB_USER: "modern_cart"
        MARIADB_PASSWORD: "test12!@"
        MARIADB_ROOT_PASSWORD: "test12!@"
